# Generated by Django 4.2.19 on 2025-02-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizeduser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
    ]
