# Generated by Django 3.2 on 2025-02-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customizeduser_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customizeduser',
            options={'default_related_name': 'users', 'ordering': ('username',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
